{"errorMessage": "unknown url type: 'LoaderURL/send/'", "errorType": "ValueError", "requestId": "d98c1000-c288-4df3-9b8b-86b1578ad94f", "stackTrace": ["  File \"/var/task/app.py\", line 11, in lambda_handler\n    req = urllib.request.Request(\n", "  File \"/var/lang/lib/python3.9/urllib/request.py\", line 320, in __init__\n    self.full_url = url\n", "  File \"/var/lang/lib/python3.9/urllib/request.py\", line 346, in full_url\n    self._parse()\n", "  File \"/var/lang/lib/python3.9/urllib/request.py\", line 375, in _parse\n    raise ValueError(\"unknown url type: %r\" % self.full_url)\n"]}